### ISSUE TITLE
adding support for Structured grid format? 

### ISSUE THREAD

**Issue by jorgepz** [trixi-framework/ReadVTK.jl#8]
Hi, thanks for your work on ReadVTK.jl, it seems a very useful tool with high potential. I am using WriteVTK.jl in some projects and at some near point I will need to read vtk files as well.

I see that your package does not support the structured grid format. Have you considered adding that? I have some matlab vtk-filereading functions and before migrating them to a simple julia version I would like to consider contributing to this...

Thanks, Jorge

**Comment by ranocha** [comment]
Thanks for your interest! As noted in the Readmme.md,

> ReadVTK was mainly motivated by wanting to write proper tests for [Trixi2Vtk.jl](https://github.com/trixi-framework/Trixi2Vtk.jl). A lot of useful features are still missing (see [below](https://github.com/trixi-framework/ReadVTK.jl#what-does-not-work)), and community contributions to improve this package are welcome!

Thus, your contributions would be welcome, I think. What does the principal developer, @sloede, think about this?

**Comment by sloede** [comment]
Hi @jorgepz, thanks a lot for reaching out! Since our group is mainly working on unstructured meshes, we do not have the requirement to be able to handle structured meshes. Having said that, we would be very happy to accept contributions to extend ReadVTK.jl's capabilites to structured meshes!

Depending on how much flexibility you need for handling different formats of structured mesh files (VTK really has *a lot* of ways to store data...), you might need to restructure some internal parts of ReadVTK.jl. However, if the goal is mainly to read in files generated by WriteVTK.jl, this shouldn't be too hard.

What I can offer is to review PRs and discuss possible implementation strategies; I will not, however, be able to contribute much in terms of actual developer time.

If you're interested to contribute, a good way to get in touch is also to join the Trixi Slack, where @ranocha, myself, and the other Trixi devs are available too (to sign up, use the "Slack" badge [here](https://github.com/trixi-framework/Trixi.jl#trixijl)).

**Comment by jorgepz** [comment]
Hi!, thanks both for your replies. I'll have a look at the code in the following days and probably contribute vìa PR or write via slack with questions.

**Comment by jorgepz** [comment]
opened draft PR for this #9
